In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import folium
from folium import plugins

#manipulating plot size
plt.rcParams['figure.figsize']=10,12

#Disabeling warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_excel('Covid cases in India.xlsx')
df_india = df.copy()
df

,S. No.,Name of State / UT,Total Confirmed cases (Indian National),Total Confirmed cases ( Foreign National ),Cured,Death
0,1,Andhra Pradesh,9,0,0,0
1,2,Bihar,3,0,0,1
2,3,Chhattisgarh,1,0,0,0
3,4,Delhi,30,1,6,1
4,5,Gujarat,32,1,0,1
5,6,Haryana,14,14,11,0
6,7,Himachal Pradesh,3,0,0,1
7,8,Karnataka,41,0,3,1
8,9,Kerala,101,8,4,0
9,10,Madhya Pradesh,9,0,0,0
10,11,Maharashtra,98,3,0,2
11,12,Manipur,1,0,0,0
12,13,Mizoram,1,0,0,0
13,14,Odisha,2,0,0,0
14,15,Puducherry,1,0,0,0
15,16,Punjab,29,0,0,1
16,17,Rajasthan,30,2,3,0
17,18,Tamil Nadu,16,2,1,0
18,19,Telengana,25,10,1,0
19,20,Chandigarh,7,0,0,0
20,21,Jammu and Kashmir,7,0,1,0
21,22,Ladakh,13,0,0,0
22,23,Uttar Pradesh,34,1,11,0
23,24,Uttarakhand,3,1,0,0
24,25,West Bengal,9,0,0,1

In [6]:
india_coord = pd.read_excel('Indian coordinates.xls')


#day by day data of india, Korea,Italy and wuhan
dbd_India= pd.read_excel('per_day_cases.xlsx',parse_dates= True, sheet_name="India")
dbd_Korea= pd.read_excel('per_day_cases.xlsx',parse_dates= True, sheet_name="Korea")
dbd_Italy= pd.read_excel('per_day_cases.xlsx',parse_dates= True, sheet_name="Italy")
dbd_Wuhan= pd.read_excel('per_day_cases.xlsx',parse_dates= True, sheet_name="Wuhan")

In [9]:
#Learn how to play around with the dataframe and create a new attribute of 'Total Case'
#Total case is the total number of confirmed cases (Indian National + Foreign National)

df.drop(['S. No.'],axis=1,inplace=True)
df['Total cases'] = df['Total Confirmed cases (Indian National)'] + df['Total Confirmed cases ( Foreign National )']
total_cases = df['Total cases'].sum()
print('Total number of confirmed COVID 2019 cases across India till date (22nd March, 2020):', total_cases)

KeyError: "['S. No.'] not found in axis"